apiVersion: v1
kind: Service
metadata:
  name: mecare-service
spec:
  selector:
    app: mecare-pod
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecare-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mecare-pod
  template:
    metadata:
      labels:
        app: mecare-pod
    spec:
      containers:
        - name: mecare-container
          image: pichayean/mecare
          resources:
            limits:
              memory: "256Mi"
              cpu: "30m"
          ports:
            - containerPort: 5173
              protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mecare-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mecare.trustmacus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mecare-service
                port:
                  number: 3000
